apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/gitops-cloud-project/my-app-repo/app-image
        ports:
        - containerPort: 80
